#pragma once

enum class PipelineDataType
{
	PIPELINE_DATA_TYPE_SHADER_RESOURCE = 0,
	PIPELINE_DATA_TYPE_SAMPLER,
	PIPELINE_DATA_CONSTANT_BUFFER,
	PIPELINE_DATA_UNORDERED,

	NUM_PIPELINE_DATA_TYPES,
};

enum class ShaderType
{
	VERTEX_SHADER_TYPE = 0,
	PIXEL_SHADER_TYPE,
	COMPUTE_SHADER_TYPE,

	NUM_SHADER_TYPES,
};

enum class PipelineType
{
	GRAPHICS_PIPELINE_TYPE = 0,
	COMPUTE_PIPELINE_TYPE,
	COPY_PIPELINE_TYPE,
	RAY_TRACE_PIPELINE_TYPE,

	NUM_PIPELINE_TYPES
};

enum class ShaderResourceType
{
	RESOURCE_TYPE_NONE = -1,
	RESOURCE_TYPE_TEXTURE_IN = 0,
	RESOURCE_TYPE_TEXTURE_OUT,
	RESOURCE_TYPE_TEXTURE_IN_OUT,
	RESOURCE_TYPE_BUFFER_IN,
	RESOURCE_TYPE_BUFFER_OUT,
	RESOURCE_TYPE_BUFFER_IN_OUT,
    
    RESOURCE_TYPE_ACCELERATION_STRUCTURE,

	NUM_RESOURCE_TYPES
};

enum class ResourceViewType
{
	NONE = -1,
	SHADER_RESOURCE_VIEW = 0,
	UNORDERED_ACCESS_VIEW,
	CONSTANT_BUFFER_VIEW,
	RENDER_TARGET_VIEW,

	NUM_VIEW_TYPES
};

enum class AttachmentType
{
	COLOR_INPUT = 0,
	COLOR_OUTPUT,
	COLOR_INPUTOUTPUT,

	DEPTH_INPUT,
	DEPTH_OUTPUT,
	DEPTH_INPUTOUT,

	NUM_ATTACHMENT_TYPES,
};

enum class AttachmentBufferType
{
	TEXTURE1D = 0,
	TEXTURE2D,
	TEXTURE3D,

	STRUCTURED,

	NUM_BUFFER_TYPES,
};
